---
- name: "smartctl_exporter | Deploy smartctl_exporter service configuration"
  ansible.builtin.template:
    src: "smartctl_exporter.service.j2"
    dest: "{{ '/etc/systemd/system/' + vars['smartctl_exporter_service'] +
      '.service' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
    - "Restart smartctl_exporter"
- name: "smartctl_exporter | Enable smartctl_exporter"
  ansible.builtin.systemd:
    name: "{{ vars['smartctl_exporter_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['smartctl_exporter'] is defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] != ''"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_enable']) is
       defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_enable']) == 'true'"
  vars:
    smartctl_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
