---
- name: "smartctl_exporter | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "smartctl_exporter | Include packages tasks [package deployment]"
  ansible.builtin.import_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['smartctl_exporter'] is defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] != ''"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_install_package'])
       is defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_install_package'])
       == 'true'"
  vars:
    smartctl_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
    smartctl_exporter_pacakges_variant:
      "{{ hostvars[inventory_hostname]['smartctl_exporter_package'] }}"
- name: "smartctl_exporter | Include packages tasks [not package deployment]"
  ansible.builtin.import_tasks:
    file: "download.yml"
  when:
    - "hostvars[inventory_hostname]['smartctl_exporter'] is defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] != ''"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_install_package'])
       is defined"
    - "hostvars[inventory_hostname]['smartctl_exporter'] |
       community.general.json_query(vars['smartctl_exporter_install_package'])
       == 'false'"
  vars:
    smartctl_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
- name: "smartctl_exporter | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_smartctl_exporter.yml"
