---
- name: "smartctl_exporter | Assert that system manager is systemd"
  assert:
    that:
      - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd"
    quiet: "true"
- name: "smartctl_exporter | Add the OS specific varibles"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: "smartctl_exporter | Set facts about smartctl_exporter role"
  ansible.builtin.set_fact:
    smartctl_exporter_version:
      "{{ hostvars[inventory_hostname]['smartctl_exporter'] |
      community.general.json_query('[].version | [0]') | default(omit) }}"
    smartctl_exporter_settings:
      "{{ hostvars[inventory_hostname]['smartctl_exporter'] |
      community.general.json_query('[].settings | [0]') | default(omit) }}"
- name: "smartctl_exporter | Get last release version from Github"
  community.general.github_release:
    user: "prometheus-community"
    repo: "smartctl_exporter"
    action: "latest_release"
  run_once: "true"
  register: "smartctl_exporter_version_tag"
  delegate_to: "localhost"
  when:
    - "vars['smartctl_exporter_version'] is defined"
    - "vars['smartctl_exporter_version'] == 'latest'"
- name: "smartctl_exporter | Set facts about smartctl_exporter role"
  ansible.builtin.set_fact:
    smartctl_exporter_version:
      "{{ vars['smartctl_exporter_version_tag']['tag'][1:] }}"
- name: "smartctl_exporter | Create smartctl_exporter catalog"
  ansible.builtin.file:
    path: "{{ vars['smartctl_exporter_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
